server:
  port : 8081

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

integration:
  starWarsApi:
    url: http://localhost:8080/api/